[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-halt = { workspace = true }
stm32f4 = { workspace = true }
misc = { path = "../misc" }

[features]
default = []